### ISSUE TITLE
Split of BRSKI-AE draft into separate documents

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-ae#19]
Proposal to split the current BRSKI-AE draft to separate the contained use cases as they have developed differently. 

- Use Case 1 targets the definition of requirements for a communication architecture using the existing BRSKI components and call model (pledge-initiator-mode, formerly PULL) to enable the use of alternative enrollment protocols for certificate enrollment (voucher handling untouched).   

- Use Case 2 targets the specification of a reversed call model (pledge-responder-mode, formerly PUSH) in which the pledge has no or only limited connectivity to a registrar or cannot initiate requests to a registrar. To facilitate the interaction between pledge and registrar, the registrar-agent component is established. The interaction between pledge and registrar-agent results in new or enhanced data objects (voucher-request-trigger, voucher-request, voucher, enrollment-request-trigger, enrollment-request). Exchanges between registrar-agent and registrar follows BRSKI (RFC8995) and EST (RFC7030), with the enhanced objects. 

Declaration of conformity to „AE“ is difficult, as the use cases have developed in different directions. Therefore the proposal to split the draft into two separate documents for use case 1 and use case 2. We may also discuss, what the target for each document would be (informational / standard RFC).

If the WG is in favor of the split, the expectation would be that the resulting document would proceed as WG documents.

**Comment by stfries** [comment]
Toerless to clarify as WG Chair and with ADs

**Comment by toerless** [comment]
We had a good first discussion about the subject
on last thursdays BRSKI-DT call and hopefully will continue it over the coming
ones.

While initially the split into two documents sounded like a useful option
based on the two separate reference architecture pictures for the
two separate use-cases == scenarios, i began to question whether the
use cases of interest would be able to support combinations of both
scenarios.

Scenario 1 introduces a "offline-site", e.g.: manufacturing plant, with
an extended registrar to support the offline backend connectivity
to MASA and CA-infra.

Scenario 2 introduces a pledge that is not initiating enrollment as
in BRSKI, but at most supporting some link-local discovery protocol
(e.g.: mDNS) and would prefer to speak afterwards a protocol wher
it is the responder, as normal in Netconf, opposed to being the
initiator as normal in BRSKI.

To me it looked very likely that the typical use-case of a manufacturing
plant would often want to have a combination of both scenarios:
The manufacturing plant might prefer to not be connected to the
Internet (== scenario 1) AND pledges want to be of the type defined
via Scenario 2.

So, while this does not say that we may not want to split up the document
into 2 in the end, it means that i would very much like to see that
the document adds a single integrated combined reference picure and
then explores how it would be possible to combine them, so that we do
not end up creating two incompatible solutions and forego the option
to build this combined scenario.

There is of course also always the variability in protocol options
specific industries prefer, and i would like to avoid having to re-specify
more than just the bare minimum when this happens instead of having to
repeat a lot of redundant normative text because we are missing a
good architectural reference document to which one can refer when adding
yet another protocol or crypto option in one part of the solution.

Meaning: I would not exclude the option yet, to split the document in
3: One that is the inclusive "reference/architecture" document that
we keep alive and extend with whatever we need to keep in common,
and then 2 or maybe over time more protocol specification parts of
the pieces we are adding.

So, just tactically, maybe just start putting a new section with
combined picture into the document, informationally discussing the
things that would need to happen (protocol wise) or this combination.
